apiVersion: v1
kind: Service
metadata:
  name: platformnpservice-srv
spec:
  selector:
    app: platformservice # this is the name of the deployment coming from platforms-depl.yaml
  ports:
    - name: platformnpservice 
      protocol: TCP
      port: 80 # this is the port that the service is listening on
      targetPort: 80 # this is the port that the container is listening on
  type: NodePort
